package com.mesi.panels.maps;

import com.mesi.MainZeldo;
import com.mesi.params.Hitbox;
import com.mesi.resources.Images;
import com.mesi.resources.Sounds;

import java.io.IOException;

/**
 * Paramétrage de l'image de fond, des blocs de collisions et de téléportation de la map.
 * L'initialisation se fait partir de la classe MapGenerator.
 */
public class Map3 extends MapModel {

    /**********  Constructors  **********/

    public Map3(Integer width, Integer height) throws IOException {
        super(width, height);

        setBackgroundImage(Images.MAP_3_BG);
        setForegroundImage(Images.MAP_3_FG);

        setScrollable(true);

        /** Coordonnées des blocs de collision **/
        getTileList().get("0,3").setTraversable(false);
        getTileList().get("0,7").setTraversable(false);
        getTileList().get("0,15").setTraversable(false);
        getTileList().get("0,22").setTraversable(false);
        getTileList().get("0,34").setTraversable(false);
        getTileList().get("0,48").setTraversable(false);
        getTileList().get("1,3").setTraversable(false);
        getTileList().get("1,21").setTraversable(false);
        getTileList().get("1,33").setTraversable(false);
        getTileList().get("1,49").setTraversable(false);
        getTileList().get("2,4").setTraversable(false);
        getTileList().get("2,6").setTraversable(false);
        getTileList().get("2,8").setTraversable(false);
        getTileList().get("2,9").setTraversable(false);
        getTileList().get("2,22").setTraversable(false);
        getTileList().get("2,34").setTraversable(false);
        getTileList().get("2,48").setTraversable(false);
        getTileList().get("3,5").setTraversable(false);
        getTileList().get("3,7").setTraversable(false);
        getTileList().get("3,9").setTraversable(false);
        getTileList().get("3,11").setTraversable(false);
        getTileList().get("3,23").setTraversable(false);
        getTileList().get("3,33").setTraversable(false);
        getTileList().get("3,49").setTraversable(false);
        getTileList().get("4,9").setTraversable(false);
        getTileList().get("4,12").setTraversable(false);
        getTileList().get("4,13").setTraversable(false);
        getTileList().get("4,22").setTraversable(false);
        getTileList().get("4,24").setTraversable(false);
        getTileList().get("4,34").setTraversable(false);
        getTileList().get("4,48").setTraversable(false);
        getTileList().get("5,10").setTraversable(false);
        getTileList().get("5,11").setTraversable(false);
        getTileList().get("5,13").setTraversable(false);
        getTileList().get("5,23").setTraversable(false);
        getTileList().get("5,25").setTraversable(false);
        getTileList().get("5,31").setTraversable(false);
        getTileList().get("5,33").setTraversable(false);
        getTileList().get("5,47").setTraversable(false);
        getTileList().get("6,14").setTraversable(false);
        getTileList().get("6,26").setTraversable(false);
        getTileList().get("6,28").setTraversable(false);
        getTileList().get("6,30").setTraversable(false);
        getTileList().get("6,32").setTraversable(false);
        getTileList().get("7,14").setTraversable(false);
        getTileList().get("7,25").setTraversable(false);
        getTileList().get("7,27").setTraversable(false);
        getTileList().get("7,29").setTraversable(false);
        getTileList().get("8,14").setTraversable(false);
        getTileList().get("8,16").setTraversable(false);
        getTileList().get("8,26").setTraversable(false);
        getTileList().get("8,29").setTraversable(false);
        getTileList().get("9,14").setTraversable(false);
        getTileList().get("9,29").setTraversable(false);
        getTileList().get("9,49").setTraversable(false);
        getTileList().get("10,14").setTraversable(false);
        for (int i = 18; i <= 27; i++) getTileList().get("10," + i).setTraversable(false);
        getTileList().get("10,29").setTraversable(false);
        getTileList().get("11,13").setTraversable(false);
        getTileList().get("11,18").setTraversable(false);
        getTileList().get("11,27").setTraversable(false);
        getTileList().get("11,29").setTraversable(false);
        getTileList().get("11,40").setTraversable(false);
        getTileList().get("12,12").setTraversable(false);
        getTileList().get("12,13").setTraversable(false);
        getTileList().get("12,18").setTraversable(false);
        getTileList().get("12,27").setTraversable(false);
        getTileList().get("12,29").setTraversable(false);
        getTileList().get("13,10").setTraversable(false);
        getTileList().get("13,11").setTraversable(false);
        getTileList().get("13,18").setTraversable(false);
        getTileList().get("13,27").setTraversable(false);
        getTileList().get("13,29").setTraversable(false);
        getTileList().get("13,32").setTraversable(false);
        getTileList().get("14,9").setTraversable(false);
        getTileList().get("14,18").setTraversable(false);
        getTileList().get("14,27").setTraversable(false);
        getTileList().get("14,29").setTraversable(false);
        getTileList().get("15,10").setTraversable(false);
        getTileList().get("15,12").setTraversable(false);
        getTileList().get("15,18").setTraversable(false);
        getTileList().get("15,27").setTraversable(false);
        getTileList().get("15,29").setTraversable(false);
        for (int i = 41; i <= 49; i++) getTileList().get("15," + i).setTraversable(false);
        getTileList().get("16,11").setTraversable(false);
        getTileList().get("16,16").setTraversable(false);
        getTileList().get("16,18").setTraversable(false);
        getTileList().get("16,27").setTraversable(false);
        getTileList().get("16,29").setTraversable(false);
        getTileList().get("16,41").setTraversable(false);
        getTileList().get("17,11").setTraversable(false);
        getTileList().get("17,18").setTraversable(false);
        getTileList().get("17,27").setTraversable(false);
        getTileList().get("17,29").setTraversable(false);
        getTileList().get("17,41").setTraversable(false);
        getTileList().get("18,12").setTraversable(false);
        getTileList().get("18,18").setTraversable(false);
        getTileList().get("18,27").setTraversable(false);
        getTileList().get("18,28").setTraversable(false);
        getTileList().get("18,29").setTraversable(false);
        getTileList().get("18,40").setTraversable(false);
        getTileList().get("19,12").setTraversable(false);
        getTileList().get("19,18").setTraversable(false);
        getTileList().get("19,27").setTraversable(false);
        getTileList().get("19,29").setTraversable(false);
        getTileList().get("19,41").setTraversable(false);
        getTileList().get("20,10").setTraversable(false);
        getTileList().get("20,13").setTraversable(false);
        getTileList().get("20,18").setTraversable(false);
        getTileList().get("20,27").setTraversable(false);
        getTileList().get("20,29").setTraversable(false);
        getTileList().get("20,41").setTraversable(false);
        getTileList().get("21,9").setTraversable(false);
        getTileList().get("21,11").setTraversable(false);
        getTileList().get("21,12").setTraversable(false);
        getTileList().get("21,13").setTraversable(false);
        getTileList().get("21,18").setTraversable(false);
        getTileList().get("21,27").setTraversable(false);
        getTileList().get("21,28").setTraversable(false);
        getTileList().get("21,29").setTraversable(false);
        getTileList().get("21,41").setTraversable(false);
        getTileList().get("22,9").setTraversable(false);
        getTileList().get("22,18").setTraversable(false);
        getTileList().get("22,27").setTraversable(false);
        getTileList().get("22,29").setTraversable(false);
        getTileList().get("22,41").setTraversable(false);
        for (int i = 10; i <= 13; i++) getTileList().get("23," + i).setTraversable(false);
        getTileList().get("23,18").setTraversable(false);
        getTileList().get("23,27").setTraversable(false);
        getTileList().get("23,29").setTraversable(false);
        getTileList().get("23,40").setTraversable(false);
        getTileList().get("24,13").setTraversable(false);
        getTileList().get("24,18").setTraversable(false);
        getTileList().get("24,27").setTraversable(false);
        getTileList().get("24,29").setTraversable(false);
        getTileList().get("24,40").setTraversable(false);
        getTileList().get("25,7").setTraversable(false);
        getTileList().get("25,8").setTraversable(false);
        getTileList().get("25,12").setTraversable(false);
        getTileList().get("25,14").setTraversable(false);
        getTileList().get("25,29").setTraversable(false);
        for (int i = 18; i <= 27; i++) getTileList().get("25," + i).setTraversable(false);
        getTileList().get("25,29").setTraversable(false);
        getTileList().get("25,41").setTraversable(false);
        getTileList().get("26,6").setTraversable(false);
        for (int i = 9; i <= 12; i++) getTileList().get("26," + i).setTraversable(false);
        getTileList().get("26,18").setTraversable(false);
        getTileList().get("26,20").setTraversable(false);
        getTileList().get("26,41").setTraversable(false);
        getTileList().get("27,6").setTraversable(false);
        getTileList().get("27,8").setTraversable(false);
        for (int i = 18; i <= 21; i++) getTileList().get("27," + i).setTraversable(false);
        getTileList().get("27,30").setTraversable(false);
        getTileList().get("27,42").setTraversable(false);
        getTileList().get("28,6").setTraversable(false);
        getTileList().get("28,42").setTraversable(false);
        getTileList().get("29,5").setTraversable(false);
        getTileList().get("29,25").setTraversable(false);
        getTileList().get("29,42").setTraversable(false);
        getTileList().get("30,5").setTraversable(false);
        getTileList().get("30,40").setTraversable(false);
        getTileList().get("30,41").setTraversable(false);
        getTileList().get("31,6").setTraversable(false);
        getTileList().get("31,40").setTraversable(false);
        getTileList().get("32,6").setTraversable(false);
        getTileList().get("32,8").setTraversable(false);
        getTileList().get("32,15").setTraversable(false);
        getTileList().get("32,41").setTraversable(false);
        getTileList().get("33,6").setTraversable(false);
        for (int i = 15; i <= 18; i++) getTileList().get("33," + i).setTraversable(false);
        for (int i = 41; i <= 49; i++) getTileList().get("33," + i).setTraversable(false);
        getTileList().get("34,5").setTraversable(false);
        getTileList().get("34,15").setTraversable(false);
        getTileList().get("34,18").setTraversable(false);
        getTileList().get("34,40").setTraversable(false);
        getTileList().get("34,46").setTraversable(false);
        getTileList().get("35,4").setTraversable(false);
        getTileList().get("35,5").setTraversable(false);
        getTileList().get("35,15").setTraversable(false);
        getTileList().get("35,18").setTraversable(false);
        getTileList().get("36,3").setTraversable(false);
        getTileList().get("36,15").setTraversable(false);
        getTileList().get("36,18").setTraversable(false);
        getTileList().get("36,47").setTraversable(false);
        getTileList().get("37,3").setTraversable(false);
        getTileList().get("37,15").setTraversable(false);
        getTileList().get("37,18").setTraversable(false);
        getTileList().get("38,2").setTraversable(false);
        getTileList().get("38,4").setTraversable(false);
        getTileList().get("38,10").setTraversable(false);
        getTileList().get("38,15").setTraversable(false);
        getTileList().get("38,18").setTraversable(false);  // Entrée marchand
        getTileList().get("38,29").setTraversable(false);
        getTileList().get("38,30").setTraversable(false);
        getTileList().get("38,49").setTraversable(false);
        getTileList().get("39,1").setTraversable(false);
        getTileList().get("39,15").setTraversable(false);
        getTileList().get("39,18").setTraversable(false);
        getTileList().get("39,28").setTraversable(false);
        getTileList().get("39,30").setTraversable(false);
        getTileList().get("39,42").setTraversable(false);
        getTileList().get("40,2").setTraversable(false);
        getTileList().get("40,4").setTraversable(false);
        getTileList().get("40,15").setTraversable(false);
        getTileList().get("40,16").setTraversable(false);
        getTileList().get("40,17").setTraversable(false);
        getTileList().get("40,18").setTraversable(false);
        getTileList().get("40,28").setTraversable(false);
        getTileList().get("40,31").setTraversable(false);
        getTileList().get("40,32").setTraversable(false);
        getTileList().get("41,1").setTraversable(false);
        getTileList().get("41,5").setTraversable(false);
        getTileList().get("41,28").setTraversable(false);
        getTileList().get("41,32").setTraversable(false);
        getTileList().get("41,46").setTraversable(false);
        for (int i = 2; i <= 11; i++) getTileList().get("42," + i).setTraversable(false);
        getTileList().get("42,23").setTraversable(false);
        getTileList().get("42,28").setTraversable(false);
        getTileList().get("42,32").setTraversable(false);
        getTileList().get("42,40").setTraversable(false);
        getTileList().get("42,45").setTraversable(false);
        getTileList().get("43,11").setTraversable(false);
        getTileList().get("43,28").setTraversable(false);
        getTileList().get("43,32").setTraversable(false);
        for (int i = 0; i <= 11; i++) getTileList().get("44," + i).setTraversable(false);
        getTileList().get("44,28").setTraversable(false);
        getTileList().get("44,31").setTraversable(false);  // Entrée première maison
        getTileList().get("44,39").setTraversable(false);
        getTileList().get("44,47").setTraversable(false);
        getTileList().get("45,10").setTraversable(false);
        getTileList().get("45,28").setTraversable(false);
        getTileList().get("45,31").setTraversable(false);
        getTileList().get("46,10").setTraversable(false);
        getTileList().get("46,28").setTraversable(false);
        getTileList().get("46,31").setTraversable(false);
        getTileList().get("46,39").setTraversable(false);
        getTileList().get("47,2").setTraversable(false);
        getTileList().get("47,10").setTraversable(false);
        getTileList().get("47,11").setTraversable(false);
        getTileList().get("47,12").setTraversable(false);
        for (int i = 28; i <= 31; i++) getTileList().get("47," + i).setTraversable(false);
        getTileList().get("47,38").setTraversable(false);
        getTileList().get("47,39").setTraversable(false);
        getTileList().get("47,42").setTraversable(false);
        getTileList().get("47,44").setTraversable(false);
        getTileList().get("48,10").setTraversable(false);
        getTileList().get("48,12").setTraversable(false);
        getTileList().get("48,37").setTraversable(false);
        getTileList().get("48,40").setTraversable(false);
        getTileList().get("48,43").setTraversable(false);
        getTileList().get("48,47").setTraversable(false);
        getTileList().get("48,49").setTraversable(false);
        getTileList().get("49,10").setTraversable(false);
        getTileList().get("49,12").setTraversable(false);  // Entrée maison près du chateau
        getTileList().get("50,10").setTraversable(false);
        getTileList().get("50,12").setTraversable(false);
        getTileList().get("50,19").setTraversable(false);
        getTileList().get("50,41").setTraversable(false);
        getTileList().get("50,42").setTraversable(false);
        getTileList().get("51,5").setTraversable(false);
        getTileList().get("51,10").setTraversable(false);
        getTileList().get("51,12").setTraversable(false);
        getTileList().get("52,10").setTraversable(false);
        getTileList().get("52,12").setTraversable(false);
        getTileList().get("52,42").setTraversable(false);
        getTileList().get("53,10").setTraversable(false);
        getTileList().get("53,12").setTraversable(false);
        for (int i = 19; i <= 23; i++) getTileList().get("53," + i).setTraversable(false);
        getTileList().get("53,12").setTraversable(false);
        getTileList().get("53,36").setTraversable(false);
        getTileList().get("54,10").setTraversable(false);
        getTileList().get("54,11").setTraversable(false);
        getTileList().get("54,12").setTraversable(false);
        getTileList().get("54,16").setTraversable(false);
        getTileList().get("54,19").setTraversable(false);
        getTileList().get("54,23").setTraversable(false);
        getTileList().get("55,19").setTraversable(false);
        getTileList().get("55,23").setTraversable(false);
        getTileList().get("56,18").setTraversable(false);
        getTileList().get("56,23").setTraversable(false);
        getTileList().get("57,19").setTraversable(false);
        getTileList().get("57,23").setTraversable(false);
        getTileList().get("58,19").setTraversable(false);
        getTileList().get("58,23").setTraversable(false);
        getTileList().get("59,10").setTraversable(false);
        getTileList().get("59,19").setTraversable(false);
        getTileList().get("59,22").setTraversable(false);
        getTileList().get("60,10").setTraversable(false);
        getTileList().get("60,19").setTraversable(false);
        getTileList().get("60,22").setTraversable(false);
        getTileList().get("61,10").setTraversable(false);
        getTileList().get("61,19").setTraversable(false);
        getTileList().get("61,22").setTraversable(false);
        getTileList().get("62,5").setTraversable(false);
        getTileList().get("62,10").setTraversable(false);
        getTileList().get("62,11").setTraversable(false);
        getTileList().get("62,19").setTraversable(false);
        getTileList().get("62,23").setTraversable(false);
        getTileList().get("63,10").setTraversable(false);
        getTileList().get("63,19").setTraversable(false);
        getTileList().get("63,23").setTraversable(false);  // Entrée maison avec un potager
        getTileList().get("63,46").setTraversable(false);
        getTileList().get("64,10").setTraversable(false);
        getTileList().get("64,19").setTraversable(false);
        getTileList().get("64,24").setTraversable(false);
        for (int i = 33; i <= 37; i++) getTileList().get("64," + i).setTraversable(false);
        getTileList().get("64,39").setTraversable(false);
        getTileList().get("64,40").setTraversable(false);
        getTileList().get("65,3").setTraversable(false);
        getTileList().get("65,10").setTraversable(false);
        for (int i = 19; i <= 23; i++) getTileList().get("65," + i).setTraversable(false);
        getTileList().get("65,33").setTraversable(false);
        getTileList().get("65,36").setTraversable(false);
        getTileList().get("65,40").setTraversable(false);
        getTileList().get("66,5").setTraversable(false);
        getTileList().get("66,10").setTraversable(false);
        getTileList().get("66,20").setTraversable(false);
        getTileList().get("66,21").setTraversable(false);
        getTileList().get("66,28").setTraversable(false);
        getTileList().get("66,33").setTraversable(false);
        getTileList().get("66,36").setTraversable(false);  // Entrée marchand d'armes
        getTileList().get("66,40").setTraversable(false);
        getTileList().get("67,10").setTraversable(false);
        getTileList().get("67,19").setTraversable(false);
        getTileList().get("67,20").setTraversable(false);
        getTileList().get("67,21").setTraversable(false);
        getTileList().get("67,33").setTraversable(false);
        getTileList().get("67,36").setTraversable(false);
        getTileList().get("67,40").setTraversable(false);
        getTileList().get("68,10").setTraversable(false);
        getTileList().get("68,33").setTraversable(false);
        getTileList().get("68,36").setTraversable(false);
        getTileList().get("68,40").setTraversable(false);
        getTileList().get("68,45").setTraversable(false);
        for (int i = 0; i <= 11; i++) getTileList().get("69," + i).setTraversable(false);
        getTileList().get("69,13").setTraversable(false);
        getTileList().get("69,33").setTraversable(false);
        getTileList().get("69,36").setTraversable(false);
        getTileList().get("69,38").setTraversable(false);
        getTileList().get("69,39").setTraversable(false);
        getTileList().get("69,40").setTraversable(false);
        getTileList().get("70,11").setTraversable(false);
        getTileList().get("70,25").setTraversable(false);
        getTileList().get("70,31").setTraversable(false);
        getTileList().get("70,33").setTraversable(false);
        getTileList().get("70,37").setTraversable(false);
        getTileList().get("70,38").setTraversable(false);
        getTileList().get("70,39").setTraversable(false);
        getTileList().get("70,40").setTraversable(false);
        for (int i = 5; i <= 11; i++) getTileList().get("71," + i).setTraversable(false);
        getTileList().get("71,33").setTraversable(false);
        getTileList().get("71,40").setTraversable(false);
        getTileList().get("71,48").setTraversable(false);
        getTileList().get("72,4").setTraversable(false);
        getTileList().get("72,8").setTraversable(false);
        getTileList().get("72,33").setTraversable(false);
        getTileList().get("72,40").setTraversable(false);
        getTileList().get("73,5").setTraversable(false);
        for (int i = 33; i <= 40; i++) getTileList().get("73," + i).setTraversable(false);
        getTileList().get("73,45").setTraversable(false);
        getTileList().get("74,4").setTraversable(false);
        getTileList().get("74,6").setTraversable(false);
        getTileList().get("74,12").setTraversable(false);
        getTileList().get("74,23").setTraversable(false);
        getTileList().get("75,3").setTraversable(false);
        getTileList().get("75,29").setTraversable(false);
        getTileList().get("75,32").setTraversable(false);
        getTileList().get("75,47").setTraversable(false);
        getTileList().get("76,4").setTraversable(false);
        getTileList().get("76,6").setTraversable(false);
        getTileList().get("76,10").setTraversable(false);
        getTileList().get("76,15").setTraversable(false);
        getTileList().get("76,26").setTraversable(false);
        getTileList().get("77,5").setTraversable(false);
        getTileList().get("77,7").setTraversable(false);
        getTileList().get("77,45").setTraversable(false);
        getTileList().get("78,6").setTraversable(false);
        getTileList().get("78,38").setTraversable(false);
        getTileList().get("78,41").setTraversable(false);
        getTileList().get("79,5").setTraversable(false);

        /** Coordonnées des blocs de téléportation et tuile de destination **/
        addTeleport(getTileList().get("0,37"), true, "MAP_1 89,15", Hitbox.WEST_BORD);
        addTeleport(getTileList().get("0,38"), true, "MAP_1 89,16", Hitbox.WEST_BORD);
        addTeleport(getTileList().get("0,39"), true, "MAP_1 89,17", Hitbox.WEST_BORD);
        addTeleport(getTileList().get("0,40"), true, "MAP_1 89,18", Hitbox.WEST_BORD);
        addTeleport(getTileList().get("0,41"), true, "MAP_1 89,19", Hitbox.WEST_BORD);
    }
}
